### ISSUE TITLE
Banner # 7 not displayed properly

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#101]
Devices: itouch 5 , Samsung S4

Portrait View
![image](https://cloud.githubusercontent.com/assets/12791909/8845084/2f9dafae-314e-11e5-8561-3d0cdb81a08a.png)

Landscape View: 
![image](https://cloud.githubusercontent.com/assets/12791909/8845091/3ce4d49e-314e-11e5-9005-281b7badb1e8.png)

**Comment by rexcebudigital** [comment]
Hi Erma, we have talked about this part with Bernard about the banner photos. We have to upload or use a bigger size image for the banner and not by using the photos in the media because our banner script cant resize a small photo. For this issue, you have used a 232x232.

As per Christian, we will remove the added photo and add a new one. Thanks.
