### ISSUE TITLE
Homepage: READ MORE should change to active state color when mouse over or when click

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#38]
![image](https://cloud.githubusercontent.com/assets/12791909/8494452/b9a1e754-2197-11e5-896a-746648199312.png)

**Comment by rexcebudigital** [comment]
Hi Erma,
First this was: 
![welcome ripe inflatable packers ripe packers](https://cloud.githubusercontent.com/assets/11186391/8611114/b529732a-26ee-11e5-8ab3-69e1d0192729.png)


And I will change this one into:
![welcome ripe inflatable packers ripe packers](https://cloud.githubusercontent.com/assets/11186391/8611080/3009f0a2-26ee-11e5-86ae-b963b8f5fc47.png)


I did not see the hover effect on this in the PSD file. So I will change the label into enhancement instead of a bug label. Thanks.
