### ISSUE TITLE
Downloadable pdf file should have an active state when mouse over

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#39]
![image](https://cloud.githubusercontent.com/assets/12791909/8496362/2bcf4a24-21a7-11e5-971c-f8eae2c0a8a1.png)

**Comment by rexcebudigital** [comment]
Hi Erma. The default hover is: 
![screenshot](https://cloud.githubusercontent.com/assets/11186391/8610958/0a938056-26ec-11e5-804b-110e095a816e.jpg)

I change it into:
![screenshot1](https://cloud.githubusercontent.com/assets/11186391/8610964/1c64e2a2-26ec-11e5-8c3f-f72c887fc0b4.jpg)

As what I know is Active state is different to Hover state or Mouse over.
I did not see any hover effect on the PSD file. So I will change the label into enhancement instead of bug label. Thanks.
