### ISSUE TITLE
Breadcrumbs will not change to active state during mouse over

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#46]
![image](https://cloud.githubusercontent.com/assets/12791909/8515111/d85df67c-23ce-11e5-851b-1c8b871ee470.png)

**Comment by rexcebudigital** [comment]
Hi Erma, I don't  see an active state design on the PSD file.
What I did is I just put a text-decoration underline on it so that it will look more visible when we hover it.
Please see the screeshot: 
![screenshot](https://cloud.githubusercontent.com/assets/11186391/8593615/ebd5d928-266b-11e5-8427-6722397335eb.jpg)

Please do let me know if there's an active state on the PSD so that I can change it asap. Thanks.

I will change the label into enhancement. But if there's really an active state, please do remove enhancement label.

**Comment by rexcebudigital** [comment]
I'm just wondering also. Why is the product title of your screenshot is not BOLD and mine is BOLD?

**Comment by ermatitan** [comment]
I have recheck it, and product title is bold in my end . Thanks
